config/routes.rb
Rails.application.routes.draw do

  root 'main#index'
  get 'dev_new' => 'main#dev_new'
  get 'user' => 'user#index'
  get 'user/profile/:id' => 'user#show'

  post 'user/new_post' => 'user#new_post'
  delete 'user/delete_post' => 'user#delete_post'

  post 'user/new_comment' => 'user#new_comment'
  delete 'user/delete_comment' => 'user#delete_comment'

  post 'user/new_repost' => 'user#new_repost'
  delete 'user/delete_repost' => 'user#delete_repost'

  post 'user/new_like' => 'user#new_like'
  delete 'user/delete_like' => 'user#delete_like'

  post 'user/follow' => 'user#follow'
  delete 'user/unfollow' => 'user#unfollow'

  get 'signup' => 'user#new'
  post 'signup' => 'user#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

end

app/controllers/main_controller.rb
class MainController < ApplicationController
  layout 'application'
  def index
    @users = User.by_created_at
  end
  #experimental, dev
  def dev_new
    @user_pass = Faker::Internet.domain_word
    @user = User.create(name: Faker::Superhero.name) do |doc|
      doc.email = Faker::Internet.free_email
      doc.password_hash = BCrypt::Password.create(@user_pass)
      doc.about = Faker::Hipster.sentence(3, false, 4)
      doc.page_name = Faker::App.name
    end
  end
end

app/views/main/dev_new.html.erb
<div class="container">
  <h3>User Generator</h3>
  <p>Created new user!</p>
  <p>
  <%= link_to 'Create another one', dev_new_path %>
  </p>
  <table style="width:100%">
    <tr>
      <td>Name</td>
      <td>Email</td>
      <td>Password</td>
      <td>About</td>
    </tr>
    <tr>
      <td><%= @user.name %></td>
      <td><%= @user.email %></td>
      <td><%= @user_pass %></td>
      <td><%= @user.about %></td>
    </tr>
  </table>
</div>

app/views/main/index.html.erb
<!-- THE SIDEBAR NO GOOD
<div class="container-fluid">
<div class="row">
<div class="col-sm-3 col-md-2 sidebar">
<ul class="nav nav-sidebar">
<li class="active"><a href="#">Overview <span class="sr-only">(current)</span></a></li>
<li><a href="#">Reports</a></li>
<li><a href="#">Analytics</a></li>
<li><a href="#">Export</a></li>
</ul>
<ul class="nav nav-sidebar">
<li><a href="">Nav item</a></li>
<li><a href="">Nav item again</a></li>
<li><a href="">One more nav</a></li>
<li><a href="">Another nav item</a></li>
<li><a href="">More navigation</a></li>
</ul>
<ul class="nav nav-sidebar">
<li><a href="">Nav item again</a></li>
<li><a href="">One more nav</a></li>
<li><a href="">Another nav item</a></li>
</ul>
</div>
<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main"><div class="row placeholders"><div class="col-xs-6 col-sm-3 placeholder"></div><div class="col-xs-6 col-sm-3 placeholder"></div><div class="col-xs-6 col-sm-3 placeholder"></div><div class="col-xs-6 col-sm-3 placeholder"></div></div>
-->
<h1 class="page-header">Users</h1>
<p>Generate a new user <%= link_to 'here', dev_new_path %></p>
  <div class="table-responsive">
  <table class="table table-striped">
  <thead>
    <tr>
      <th>#</th>
      <th>Name</th>
      <th>Email</th>
      <th>About</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each_with_index do |user, index| %>
    <tr>
      <td><%= index + 1 %></td>
      <td><%= link_to user.name, controller: 'user', action: 'show', id: user.id %></td>
      <td><%= user.email %></td>
      <td><%= user.about %></td>
    </tr>
    <% end %>
  </tbody>
  </table>
</div>
<!-- SIDEBAR NO GOOD
</div>
</div>
</div>
-->