config/routes.rb
Rails.application.routes.draw do

  root 'main#index'
  get 'dev_new' => 'main#dev_new'
  get 'user' => 'user#index'
  get 'user/profile/:id' => 'user#show'

  post 'user/new_post' => 'user#new_post'
  delete 'user/delete_post' => 'user#delete_post'

  post 'user/new_comment' => 'user#new_comment'
  delete 'user/delete_comment' => 'user#delete_comment'

  post 'user/new_repost' => 'user#new_repost'
  delete 'user/delete_repost' => 'user#delete_repost'

  post 'user/new_like' => 'user#new_like'
  delete 'user/delete_like' => 'user#delete_like'

  post 'user/follow' => 'user#follow'
  delete 'user/unfollow' => 'user#unfollow'

  get 'signup' => 'user#new'
  post 'signup' => 'user#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

end

app/models/user.rb
class User < CouchRest::Model::Base
  collection_of :posts
  collection_of :reposts
  collection_of :comments
  collection_of :likes
  collection_of :private_chats
  property :name, String
  property :email, String
  property :password_hash, String
  property :about, String, default: "Blank"
  property :page_name, String
  property :followers, [String]
  property :following, [String]
  timestamps!

  design do
    view :by_password_hash
    view :by_name
    view :by_email
    view :by_page_name
    view :by_created_at
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
  layout 'application'
  def index
    if logged_in?
      @user = current_user
    else
      redirect_to login_path
    end
    @postables = Postable.by_created_at
  end

  def show
    @user = User.find params[:id]
    @postables = Post.by_created_at
  end

  #signup_path is here
  def new
    #TODO clean this up with usage of session data
    valid_fields = true

    #less clear but more efficient
    #if there is no user submitted data then the fields are not valid
    if !params[:user].nil?
      name = params[:user][:name]
      email = params[:user][:email]
      password = params[:user][:password]
      confirm_password = params[:user][:confirm_password]

      #empty fields?
      if name.nil? || email.nil? || password.nil? || confirm_password.nil?
        valid_fields = false
      end
      #password same?
      if password != confirm_password
        valid_fields = false
      end
      #email unique?
      if User.find_by_email(email)
        #not unique
        valid_fields = false
      end
    else
      valid_fields = false
    end

    #if not valid then refreshes page
    if !valid_fields
    else
      #if everything checks out then create the user
      user = User.create(name: name) do |doc|
        doc.email = email
        doc.password_hash = BCrypt::Password.create(password)
        redirect_to action: 'index'
      end
    end
  end

  #create repost on a post
  def new_repost
    user = current_user
    post = Post.find params[:post_id]
    repost = Repost.find get_user_post_repost_id(user, post)
    if repost
      if repost.deleted
        repost.deleted = false
        repost.save
      end
    else
      repost = Repost.new(message: params[:message]) do |doc|
        doc.user = user
        doc.post = post
      end
      repost.save
      post.reposts << repost
      user.reposts << repost
      user.save
      post.save
    end

    redirect_to :back
  end

  #create comment on a post
  def new_comment
    user = current_user
    post = Post.find params[:post_id]
    comment = Comment.new(message: params[:message]) do |doc|
      doc.user = user
      doc.post = post
    end
    comment.save
    post.comments << comment
    user.comments << comment
    user.save
    post.save
    
    redirect_to :back
  end

  #changes to comment removed
  def delete_comment
    comment = Comment.find params[:comment_id]
    comment.deleted = true
    comment.save
    redirect_to :back
  end

  #like something that was posted
  def new_like
    user = current_user
    postable = Postable.find params[:postable_id]
    like = Like.find get_user_postable_like_id(user, postable)
    if like
      if like.deleted
        like.deleted = false
        like.save
      end
    else
      like = Like.new(user: user) do |doc|
        doc.postable = postable
      end
      like.save
      user.likes << like
      postable.likes << like
      user.save
      postable.save
    end

    redirect_to :back
  end

  #create post
  def new_post
    user = current_user
    message = params[:message]
    post = Post.new(message: message) do |doc|
      doc.user = user
    end
    post.save
    user.posts << post
    user.save

    redirect_to :back
  end

  #deletes post's id from user's post_ids property, however the post will still exist
  def delete_repost
    repost = Repost.find params[:repost_id]
    repost.deleted = true
    repost.save

    redirect_to :back
  end

  def delete_like
    like = Like.find params[:like_id]
    like.deleted = true
    like.save

    redirect_to :back
  end

  #deletes post's id from user's post_ids property, however the post will still exist
  def delete_post
    post = Post.find params[:post_id]
    post.deleted = true
    post.save

    redirect_to :back
  end

  def follow
    user = current_user
    other_user = User.find params[:user_id]
    user.following << other_user.id
    user.save
    other_user.followers << user.id
    other_user.save
    redirect_to :back
  end

  def unfollow
    user = current_user
    other_user = User.find params[:user_id]
    user.following.delete other_user.id
    user.save
    other_user.followers.delete user.id
    other_user.save
    redirect_to :back
  end
end

app/helpers/user_helper.rb
module UserHelper
    def user_is_following(user, other_user)
        user.following.each do |f|
            if f == other_user.id
                return true
            end
        end
        return false
    end

    def get_user_post_repost_id(user, post)
        post = Post.find post.id
        post.reposts.each do |r|
            if r.user == user
                return r.id
            end
        end

        return nil
    end

    def get_user_postable_like_id(user, postable)
        postable = Postable.find postable.id
        postable.likes.each do |l|
            if l.user == user
                return l.id
            end
        end

        return nil
    end

    def get_postable_visible_likes_count(postable)
        count = 0
        likes = Like.by_postable_id.key(postable.id)
        likes.each do |l|
            if l.visible && !l.deleted
                count += 1
            end
        end
        return count
    end

    def get_post_visible_reposts_count(post)
        count = 0
        reposts = Repost.by_post_id.key(post.id)
        reposts.each do |r|
            if r.visible && !r.deleted
                count += 1
            end
        end
        return count
    end

    def get_user_visible_posts_count(user)
        count = 0
        posts = Post.by_user_id.key(user.id)
        posts.each do |p|
            if p.visible && !p.deleted
                count += 1
            end
        end
        return count
    end

    #checks if user has liked something that has been posted
    def user_has_liked?(user, postable)
        postable.likes.each do |l|
            if l.user == user
                if !l.deleted
                    return true
                end
            end
        end
        return false
    end

    #check to see if the user has reposted a post
    def user_has_reposted?(user, post)
        if (!post.instance_variable_defined?(:@reposts))
            return false;
        end
        post.reposts.each do |r|
            #if it was reposted by the user
            if r.user == user
                #deleted means it's archived but is seen as if he canceled
                if !r.deleted
                    #if the user has reposted it and he did not "delete" it, then user can repost
                    return true
                end
            end
        end
        return false
    end

    #check if user can repost
    def user_can_repost?(user, post)
        #if user author of post or has reposted it already
        if post.user_id == user.id || user_has_reposted?(user, post)
            return false
        end
        return true
    end

    #check if user can like
    def user_can_like?(user, postable)
        if postable.user_id == user.id || user_has_liked?(user, post)
            return false
        end
        return true
    end
end

app/views/user/index.html.erb
<%= stylesheet_link_tag 'timeline' %>
<div class="timeline">
  <div class="container timeline-container">

    <div class="row">
      <div class="col">
        <div class="login-panel panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Hello, <%= @user.name %></h3>
          </div>
          <div class="panel-body">
            <%= form_tag controller: 'user', action: 'new_post', method: 'post' do %>
              <div class="form-group">
                <%= text_area_tag(:message, '', required: '', placeholder: "Say something, I'm giving up on you.", rows: '3', class: 'form-control') %>
              </div>
              <%= submit_tag('Post', class: 'btn btn-sm btn-success') %>
            <% end %>
          </div>
        </div><!-- login-panel -->
      </div>
    </div><!-- row -->

    <!-- BEFORE RENDERING -->
    <%= render 'shared/user_following' %>
    <%= render 'shared/user_followers' %>
    <br><br>
    <%= render 'shared/user_postables' %>
  </div>
</div>

app/views/user/new.html.erb
<%= stylesheet_link_tag 'signin' %>
<div class="container">
  <%= form_for :user, url: signup_path, method: 'post', html: { class: 'form-signin' } do |f| %>
    <h2 class="form-signin-heading">Sign Up</h2>

    <%= f.label :email, 'Email address ', class: 'sr-only' %>
    <%= f.email_field :email, placeholder: 'Email address', autofocus: '', type: 'email', class: 'form-control' %>

    <%= f.label :name, 'Name ', class: 'sr-only' %>
    <%= f.text_field :name, placeholder: 'Name', type: 'text', class: 'form-control' %>

    <%= label_tag :Password, 'Password ', class: 'sr-only' %>
    <%= f.password_field :password, placeholder: 'Password', type: 'password', class: 'form-control' %>

    <%= label_tag :confirm_password, 'Confirm Password ', class: 'sr-only' %>
    <%= f.password_field :confirm_password, placeholder: 'Confirm Password', type: 'password', class: 'last form-control' %>

    <%= f.submit 'Sign Up', class: 'btn btn-lg btn-primary btn-block' %>

  <% end %>
  <!--< %= button_to 'Log in', login_path, method: 'get', form_class: 'form-signin', class: 'btn btn-lg btn-info btn-block second-btn' %>-->
</div>

app/views/user/show.html.erb
<%= stylesheet_link_tag 'timeline' %>
<div class="timeline">
  <div class="container timeline-container">
    <div class="profile">
      <h3>User Profile</h3>
      <div class="follow">
        <% if current_user == @user || current_user == nil %>
        <% elsif user_is_following(current_user, @user) %>
          <%= link_to 'Unfollow', user_unfollow_path(user_id: @user.id), method: 'delete' %>
        <% else %>
          <%= link_to 'Follow', user_follow_path(user_id: @user.id), method: 'post' %>
        <% end %>
      </div>
      <div class="name">Name: <%= @user.name %></div>
      <div class="email">Email: <%= @user.email %></div>
      <div class="about">
        About me: <%= @user.about %>
      </div>
    </div>
    <%= render 'shared/user_following' %>
    <%= render 'shared/user_followers' %>
    <br><br>
    <%= render 'shared/user_postables' %>
  </div>
</div>