config/routes.rb
Rails.application.routes.draw do

  root 'main#index'
  get 'dev_new' => 'main#dev_new'
  get 'user' => 'user#index'
  get 'user/profile/:id' => 'user#show'

  post 'user/new_post' => 'user#new_post'
  delete 'user/delete_post' => 'user#delete_post'

  post 'user/new_comment' => 'user#new_comment'
  delete 'user/delete_comment' => 'user#delete_comment'

  post 'user/new_repost' => 'user#new_repost'
  delete 'user/delete_repost' => 'user#delete_repost'

  post 'user/new_like' => 'user#new_like'
  delete 'user/delete_like' => 'user#delete_like'

  post 'user/follow' => 'user#follow'
  delete 'user/unfollow' => 'user#unfollow'

  get 'signup' => 'user#new'
  post 'signup' => 'user#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

end

app/views/scrapped/_user_posts.html.erb
<h3><% if current_user == @user %>Your<% else %><%= @user.name%>'s<% end %> posts:</h3>
<%= 'For admin purposes: ' %>
<br>
<%= 'Total posts: ' + Post.by_user_id.key(@user.id).count.to_s %>
<br>
<%= 'Visible posts: ' + get_user_visible_posts_count(@user).to_s %>
<% @user.posts.reverse_each do |post| %>
  <% if post.nil? || post.deleted || !post.visible then next end %>
  <p>
    <%= post.created_at %>
    <br>
    By <%= post.user.name ? link_to(post.user.name, { controller: 'user', action: 'show', id: post.user.id }) : 'N/A'%>
  <br>

  <%= get_postable_visible_likes_count(post) %>
  <% if !logged_in? %>
    <%= 'Likes' %>
  <% elsif user_has_liked?(current_user, post) %>
    <%= link_to 'You liked this', user_delete_like_path(like_id: get_user_postable_like_id(current_user, post)), method: 'delete' %>
  <% else %>
    <%= link_to 'Like', user_new_like_path(postable_id: post.id), method: 'post' %>
  <% end %>

  <%= get_post_visible_reposts_count(post) %>
  <% if !logged_in? || post.user == current_user %>
    <%= 'Reposts' %>
  <% elsif user_has_reposted?(current_user, post) %>
    <%= link_to 'You reposted this', user_delete_repost_path(repost_id: get_user_post_repost_id(current_user, post)), method: 'delete' %>
  <% else %>
    <%= link_to 'Repost', user_new_repost_path(post_id: post.id), method: 'post' %>
  <% end %>

  <% if post.user == current_user %><%= link_to 'Delete', user_delete_post_path(post_id: post.id), method: 'delete' %><% end %>
    <br> <%= post.message %>
    <br>
    <div style="padding-left: 20px">
      <b><%= post.comments.count %> comments:</b>
      <br>
      <% post.comments.each do |comment| %>
        <% if comment.nil? || comment.deleted || !comment.visible then next end %>
          By <%= link_to comment.user.name, { controller: 'user', action: 'show', id: comment.user.id }  %>

        <%= get_postable_visible_likes_count(comment) %>

        <% if !logged_in? %>
          <%= 'likes' %>
        <% elsif user_has_liked?(current_user, comment) %>
          <%= link_to 'You liked this', user_delete_like_path(like_id: get_user_postable_like_id(current_user, comment)), method: 'delete' %>
        <% else %>
          <%= link_to 'Like', user_new_like_path(postable_id: comment.id), method: 'post' %>
        <% end %>

        <% if comment.user == current_user %>
          <%= link_to('delete', user_delete_comment_path(comment_id: comment.id), method: 'delete') %>
        <% end %>
        <br>
        <%= comment.message %>
        <br>
        <br>

      <% end %>

      <%= form_tag controller: 'user', action: 'new_comment', method: 'post', post_id: post.id do %>
      <%= text_area_tag(:message, "", size: "28x2") %>
      <br>
      <%= submit_tag('Comment') %>
    <% end %>
    </div>
    <br>
    <br>
  </p>
<% end %>

app/views/scrapped/_user_reposts.html.erb
<h3><% if current_user == @user %>Your<% else %><%= @user.name%>'s<% end %> reposts:</h3>
<%= 'Total (includes deleted and not visible) reposts: ' + Repost.by_user_id.key(@user.id).count.to_s %>
<br>
<br>
<% @user.reposts.reverse_each do |repost| %>
  <% if repost.deleted || !repost.visible then next end %>
  <% post = repost.post %>
  <%= post.created_at %>
  <br>
  By <%= link_to post.user.name, controller: 'user', action: 'show', id: post.user.id, method: 'get' %>
  <br>

  <%= get_postable_visible_likes_count(post) %>
  <% if !logged_in? %>
    <%= 'likes' %>
  <% elsif user_has_liked?(current_user, post) %>
    <%= link_to 'You liked this', user_delete_like_path(like_id: get_user_postable_like_id(current_user, post)), method: 'delete' %>
  <% else %>
    <%= link_to 'Like', user_new_like_path(postable_id: post.id), method: 'post' %>
  <% end %>

  <% if repost.user == current_user %><%= link_to('Depost', user_delete_repost_path(repost_id: repost.id), method: 'delete') %><% end %>
  <br>
  <%= post.message %>
  <br>
  <%= post.comments.count %> comments
  <br>
  <!-- TODO THIS:
  Repost Message: < %= repost.message.nil? ? 'Blank' : repost.message %>
  <br>
  <br>
  -->
<% end %>