config/routes.rb
Rails.application.routes.draw do

  root 'main#index'
  get 'dev_new' => 'main#dev_new'
  get 'user' => 'user#index'
  get 'user/profile/:id' => 'user#show'

  post 'user/new_post' => 'user#new_post'
  delete 'user/delete_post' => 'user#delete_post'

  post 'user/new_comment' => 'user#new_comment'
  delete 'user/delete_comment' => 'user#delete_comment'

  post 'user/new_repost' => 'user#new_repost'
  delete 'user/delete_repost' => 'user#delete_repost'

  post 'user/new_like' => 'user#new_like'
  delete 'user/delete_like' => 'user#delete_like'

  post 'user/follow' => 'user#follow'
  delete 'user/unfollow' => 'user#unfollow'

  get 'signup' => 'user#new'
  post 'signup' => 'user#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <p class="text-muted">
    &copy; 2016
    <% if Date.today.year > 2016 %>
      - <%= Date.today.year %>
    <% end %>
    Lazy Ass Craig Corporations. All rights reserved.
    </p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<%= stylesheet_link_tag 'main' %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      </button>
      <%= link_to 'Estood', '/', class: 'navbar-brand' %>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right navbar-form">

        <% if logged_in? %>
          <li><input type="text" class="form-control" placeholder="Search..."></li>

          <li><%= link_to current_user.name, user_path %></li>
          <li><%= link_to 'Logout', logout_path, method: 'delete' %></li>

        <% else %>

          <!-- TODO MAKE WORKS GOOD--> 
          <div class="sr-only">
            <li><% link_to 'Sign In', login_path %></li>
            <li><% link_to 'Sign Up', signup_path %></li>
          </div>

          <!-- TODO UGLY IN MOBILE VIEW -->
          <%= form_for :session, url: login_path, method: 'post' do |f| %>
            <%= f.email_field :email, placeholder: 'Email', type: 'email', class: 'form-control' %>
            <%= f.password_field :password, placeholder: 'Password', type: 'password', class: 'form-control' %>
            <%= f.submit 'Sign In', class: 'btn btn-success' %>
            <%= link_to 'New Account', signup_path, method: 'get', class: 'btn btn-secondary' %>
          <% end %>

        </div>

        <% end %>

      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Estood</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
    <![endif]-->
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container-fluid">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>